--Tipo de Usuários

INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Voluntário');
INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Necessitado');
INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Apoiador');
INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Administrador');


-- Usuários

INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL,1, 'Pedro Henrique', 'pedro@email.com', '123pedro', TO_DATE('30/05/2025 08:00:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 2, 'Carla Dias', 'carla@email.com', 'abc123', TO_DATE('30/05/2025 08:10:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 1, 'João Almeida', 'joao@email.com', 'senha456', TO_DATE('30/05/2025 08:20:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 3, 'Beatriz Rocha', 'bia@email.com', 'btr2025', TO_DATE('30/05/2025 08:30:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 2, 'Lucas Ferreira', 'lucas@email.com', 'lucas789', TO_DATE('30/05/2025 08:40:00', 'DD/MM/YYYY HH24:MI:SS'));

