--Tipo de Usuários

INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Voluntário');
INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Necessitado');
INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Apoiador');
INSERT INTO T_SMP_TIPO_USUARIOS (ID_TIPO_USUARIO, NOME_TIPO) VALUES (SEQ_TIPO_USUARIOS_ID_TIPO_USUARIOS.NEXTVAL,'Administrador');

-- Tipo de Recursos

INSERT INTO T_SMP_TIPO_RECURSOS (ID_RECURSO, RECURSO) VALUES (SEQ_TIPO_RECURSOS_ID_RECURSO.NEXTVAL, 'Alimentos');
INSERT INTO T_SMP_TIPO_RECURSOS (ID_RECURSO, RECURSO) VALUES (SEQ_TIPO_RECURSOS_ID_RECURSO.NEXTVAL, 'Roupas');
INSERT INTO T_SMP_TIPO_RECURSOS (ID_RECURSO, RECURSO) VALUES (SEQ_TIPO_RECURSOS_ID_RECURSO.NEXTVAL, 'Medicamentos');
INSERT INTO T_SMP_TIPO_RECURSOS (ID_RECURSO, RECURSO) VALUES (SEQ_TIPO_RECURSOS_ID_RECURSO.NEXTVAL, 'Brinquedos');
INSERT INTO T_SMP_TIPO_RECURSOS (ID_RECURSO, RECURSO) VALUES (SEQ_TIPO_RECURSOS_ID_RECURSO.NEXTVAL, 'Móveis');

-- Tipo de Zonas

INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Urbana');
INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Rural');
INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Periurbana');
INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Centro');
INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Leste');
INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Oeste');
INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Norte');
INSERT INTO T_SMP_TIPO_ZONAS (ID_ZONA, ZONA) VALUES (SEQ_TIPO_ZONAS_ID_ZONA.NEXTVAL, 'Sul');

-- Usuários

INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL,1, 'Pedro Henrique', 'pedro@email.com', '123pedro', TO_DATE('30/05/2025 08:00:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 2, 'Carla Dias', 'carla@email.com', 'abc123', TO_DATE('30/05/2025 08:10:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 1, 'João Almeida', 'joao@email.com', 'senha456', TO_DATE('30/05/2025 08:20:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 3, 'Beatriz Rocha', 'bia@email.com', 'btr2025', TO_DATE('30/05/2025 08:30:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_USUARIOS (ID_USUARIO, ID_TIPO_USUARIO, NOME, EMAIL, SENHA, DATA_CRIACAO) VALUES (SEQ_USUARIOS_ID_USUARIO.NEXTVAL, 2, 'Lucas Ferreira', 'lucas@email.com', 'lucas789', TO_DATE('30/05/2025 08:40:00', 'DD/MM/YYYY HH24:MI:SS'));

-- Ajudas
INSERT INTO T_SMP_AJUDAS (ID_AJUDA, ID_USUARIO, ID_RECURSO, DESCRICAO, STATUS, DATA_PUBLICACAO) VALUES (SEQ_AJUDAS_ID_AJUDA.NEXTVAL, 1, 1, 'Doação de alimentos não perecíveis', '1', TO_DATE('01/06/2025 10:00:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_AJUDAS (ID_AJUDA, ID_USUARIO, ID_RECURSO, DESCRICAO, STATUS, DATA_PUBLICACAO) VALUES (SEQ_AJUDAS_ID_AJUDA.NEXTVAL, 2, 2, 'Doação de roupas infantis', '1', TO_DATE('02/06/2025 11:00:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_AJUDAS (ID_AJUDA, ID_USUARIO, ID_RECURSO, DESCRICAO, STATUS, DATA_PUBLICACAO) VALUES (SEQ_AJUDAS_ID_AJUDA.NEXTVAL, 3, 3, 'Doação de medicamentos para idosos', '1', TO_DATE('03/06/2025 12:00:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_AJUDAS (ID_AJUDA, ID_USUARIO, ID_RECURSO, DESCRICAO, STATUS, DATA_PUBLICACAO) VALUES (SEQ_AJUDAS_ID_AJUDA.NEXTVAL, 4, 4, 'Doação de brinquedos para crianças carentes', '1', TO_DATE('04/06/2025 13:00:00', 'DD/MM/YYYY HH24:MI:SS'));
INSERT INTO T_SMP_AJUDAS (ID_AJUDA, ID_USUARIO, ID_RECURSO, DESCRICAO, STATUS, DATA_PUBLICACAO) VALUES (SEQ_AJUDAS_ID_AJUDA.NEXTVAL, 5, 5, 'Doação de móveis usados', '1', TO_DATE('05/06/2025 14:00:00', 'DD/MM/YYYY HH24:MI:SS'));

-- Localizações

INSERT INTO T_SMP_LOCALIZACOES (ID_LOCALIZACAO, ID_AJUDA, ID_ZONA, LATITUDE, LONGITUDE) VALUES (SEQ_LOCALIZACOES_ID_LOCALIZACAO.NEXTVAL, 1, 1, -23.550520, -46.633308);
INSERT INTO T_SMP_LOCALIZACOES (ID_LOCALIZACAO, ID_AJUDA, ID_ZONA, LATITUDE, LONGITUDE) VALUES (SEQ_LOCALIZACOES_ID_LOCALIZACAO.NEXTVAL, 2, 2, -23.550520, -46.633308);
INSERT INTO T_SMP_LOCALIZACOES (ID_LOCALIZACAO, ID_AJUDA, ID_ZONA, LATITUDE, LONGITUDE) VALUES (SEQ_LOCALIZACOES_ID_LOCALIZACAO.NEXTVAL, 3, 3, -23.550520, -46.633308);
INSERT INTO T_SMP_LOCALIZACOES (ID_LOCALIZACAO, ID_AJUDA, ID_ZONA, LATITUDE, LONGITUDE) VALUES (SEQ_LOCALIZACOES_ID_LOCALIZACAO.NEXTVAL, 4, 4, -23.550520, -46.633308);
INSERT INTO T_SMP_LOCALIZACOES (ID_LOCALIZACAO, ID_AJUDA, ID_ZONA, LATITUDE, LONGITUDE) VALUES (SEQ_LOCALIZACOES_ID_LOCALIZACAO.NEXTVAL, 5, 5, -23.550520, -46.633308);
